// 主题列表
export const UPDATE_LIST = 'UPDATE_LIST'
export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS'
export const UPDATE_LIST_ERROR = 'UPDATE_LIST_ERROR'

// 主题详情
export const UPDATE_DETAIL = 'UPDATE_DETAIL'
export const UPDATE_DETAIL_SUCCESS = 'UPDATE_DETAIL_SUCCESS'
export const UPDATE_DETAIL_ERROR = 'UPDATE_DETAIL_ERROR'

// 用户详情
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'